### ISSUE TITLE
Aircraft.getBearing should be moved to Vector2D

### ISSUE THREAD

**Issue by jcowgill** [sepr-hou/atc-game#30]
- [x] Aircraft.getBearing()
- [x] Aircraft.calculateAngle()

Aircraft.calculateAngle seems to be similar to getBearing. Do we need 2 methods to do this?

**Comment by thisisrobkerry** [comment]
I think we only need one!

**Comment by thisisrobkerry** [comment]
CalculateAngle is needed in Aircraft, without it, landing breaks. Get Bearing is fine.

**Comment by jcowgill** [comment]
Yes but calculateAngle is still "the same" as getBearing. All uses of it should be changed to vector.getBearing()

**Comment by thisisrobkerry** [comment]
calculateAngle should actually return the angle between the aircraft and a point I believe. It was badly documented and implemented

**Comment by thisisrobkerry** [comment]
I'm being an idiot, I've sorted it! I'll tidy my mess then commit
