### ISSUE TITLE
Get the GUI working

### ISSUE THREAD

**Issue by jcowgill** [sepr-hou/atc-game#5]
To do this we need a **DESIGN** for the GUI (what it will look like + what the controls are etc). Once we have actually made a decision (and asked tim? - it may be a bit late?), things will become much easier.

Once that is done, it's a case of doing lots of libGDX stuff and joining it to the logic side.
- [x] Timer
- [x] Aircraft images
- [x] Game over screen
- [x] Fix background image of control panel
- [x] Maximum number of flights (in new-flightplan-generation branch)
- [x] Fix aircraft generation so flights don't keep colliding with each other (in new-flightplan-generation branch)
- [x] Control panel
- [x] Show flight path / waypoints etc.
- [x] Are entry + exit points ok?
- [ ] Collision warnings
- [x] Fonts
- [x] Colours (of waypoints?)
- [x] Control panel - flight number
- [ ] Control panel - position indicator
##### Not for this assessment
- More accurate collision detection algorithm - do we need this for assessment 2?

**Comment by thisisrobkerry** [comment]
I can't seem to get the logo to render onto the control panel. I've created a batch and drawn it but just get empty space with no errors!

**Comment by jcowgill** [comment]
If the logo isn't changing, it's probably easier to use an [Image](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/ui/Image.html) actor (like how the background is drawn in the MenuScreen) rather than rendering it manually with a batch.

**Comment by thisisrobkerry** [comment]
I'll give that a go

**Comment by thisisrobkerry** [comment]
works fine!

**Comment by jcowgill** [comment]
So exactly what still needs to be done on the GUI?

**Comment by jk1993** [comment]
If we get a chance we can take a look at making the fonts look a bit nicer rather than scaled. I guess we need to decide exactly how the collision warnings will look and finalize the colours of different things
